### ISSUE TITLE
Improve the installation method

### ISSUE THREAD

**Issue by lyz-code** [lyz-code/pydo#11]
Right now we need to create the `~/.local/share/pydo` directory and initialize an empty database (as stated in the README.md).

This problem arises because the `install` function needs the `session` object. Which makes no sense because the database doesn't exist yet.

So we'll need to remove that requirement, and create the session inside the `install` function.

**Comment by lytex** [comment]
Also the requirements are not installed when running `pip3 install git+git://github.com/lyz-code/pydo`. Right now you first have to clone the repo, `pip3 -r requirements.txt` and then install pydo

**Comment by d3vv3** [comment]
> `pip3 -r requirements.txt` 
would be `pip3 install -r requirements.txt`

**Comment by lyz-code** [comment]
Requirements are now installed with pip via https://github.com/lyz-code/pydo/pull/20

**Comment by lyz-code** [comment]
Also, it would be nice that the user didn't need to execute `pydo install` when installing or when an upgrade in the database schema is done.

To solve it I see two solutions:

* Modify `setup.py` configuration so that it run `pydo install` once the installation is finished.
* Modify `pydo/__init__.py` so that each time the command is run it checks if the `~/.local/share/pydo/main.db` file exists, if it doesn't then it runs the `install` function. Also for the database schema upgrades. We can store the version of pydo in the ddbb, and also add in `__init__.py` a check that compares the program version with the version stored in the ddbb. If it's not the same, it can execute the `install` function.

I think the first solution is cleaner and adds less overhead to each `pydo` execution.

**Comment by lytex** [comment]
The first solution should be implemented on PR #60 . We could also add the migration inside the `except FileExistsError:` code block in the future.
