### ISSUE TITLE
Add recurrence support

### ISSUE THREAD

**Issue by lyz-code** [lyz-code/pydo#2]
Allow tasks to have a recurrence of two kinds:

* Repeating
* Recurring

Check out [my taskwarrior plugin](https://github.com/lyz-code/taskwarrior_recurrence) to fix recurrence and [tasklite recurrence definition](https://tasklite.org/concepts.html) for more information.

**Comment by lyz-code** [comment]
@lytex I've updated the plugin url

**Comment by lyz-code** [comment]
There is also information in the [pydo date docs](https://lyz-code.github.io/pydo/dates/) about the date parser.

**Comment by lytex** [comment]
This link is currently broken:

> There is also information in the [pydo date docs](https://lyz-code.github.io/pydo/dates/) about the date parser.

I think you meant
https://lyz-code.github.io/pydo/advanced_usage/dates/
