### ISSUE TITLE
Adding/modifying empty attributes

### ISSUE THREAD

**Issue by m0wer** [lyz-code/pydo#27]
Depending on the attribute an error is thrown or a project/task without a title is created.

Adding empty attributes shouldn't be allowed. In the case of `mod` it would be nice if setting an empty attribute sets its value back to `None` (except for the title) or throws an error if it didn't already exist.

**Comment by lyz-code** [comment]
We could solve this if in the `_set` method, the default value for the arguments is `unchanged` instead of `None`
