### ISSUE TITLE
pydo installation fails

### ISSUE THREAD

**Issue by lytex** [lyz-code/pydo#74]
**I'm using python3.8**
Installation fails with either
`pip3 install git+git://github.com/lyz-code/pydo`
or installing pydo manually.

```
    ERROR: Command errored out with exit status 255:
     command: /home/julian/.virtualenvs/pydo/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/julian/code/python/pydo/setup.py'"'"'; __file__='"'"'/home/julian/code/python/pydo/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/julian/code/python/pydo/
    Complete output (14 lines):
    running egg_info
    creating pydo.egg-info
    writing pydo.egg-info/PKG-INFO
    writing dependency_links to pydo.egg-info/dependency_links.txt
    writing entry points to pydo.egg-info/entry_points.txt
    writing requirements to pydo.egg-info/requires.txt
    writing top-level names to pydo.egg-info/top_level.txt
    writing manifest file 'pydo.egg-info/SOURCES.txt'
    reading manifest file 'pydo.egg-info/SOURCES.txt'
    writing manifest file 'pydo.egg-info/SOURCES.txt'
    [alembic.runtime.migration] Context impl SQLiteImpl.
    [alembic.runtime.migration] Will assume non-transactional DDL.
    [alembic.util.messaging] Can't locate revision identified by 'ade851e4a70f'
    FAILED: Can't locate revision identified by 'ade851e4a70f'
    ----------------------------------------
ERROR: Command errored out with exit status 255: python setup.py egg_info Check the logs for full command output.
```

**Comment by lytex** [comment]
Solved, there was an old database interfering with installation. Unless you have some important data you can simply do `rm ~/.local/share/pydo/main.db `

**Comment by lyz-code** [comment]
I feel that an explanation needs to be given. Until we reach 1.0.0 we can't assure that the database schema is stable, that together with the fact that alembic doesn't yet manage table alteration operations in sqlite, means that it's easier to reinitialize the alembic repository when a database schema is needed.

We know that it's not a sustainable solution, and we'll dive further into the existing solutions for this problem once we reach the first stable release.

For now, if you don't want to loose your data between pydo upgrades, you can use the `export` feature, and once the `import` is done you can import it back. Or you can wait for that moment to upgrade pydo
